// <auto-generated />
using System;
using Jabartah.Trivia.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jabartah.Trivia.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904141508_AddPasswordExtraTimePowerUp")]
    partial class AddPasswordExtraTimePowerUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jabartah.Trivia.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.GameSessions.GameQuestionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivePowerUp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("AttemptFailed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PowerUpTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RevealedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TurnTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WonByTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId", "QuestionId")
                        .IsUnique();

                    b.ToTable("GameQuestionStates", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.GameSessions.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("CategoryIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentTurnTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.PasswordGame.PasswordCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("PasswordCategories", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.PasswordGame.PasswordGameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("CategoryIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundsPerTeam")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordGameSessions", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.PasswordGame.PasswordRevealToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PasswordRoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PasswordWordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PasswordRoundId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PasswordRevealTokens", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.PasswordGame.PasswordRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PasswordGameSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PasswordWordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PasswordGameSessionId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("PasswordRounds", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.PasswordGame.PasswordTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("ExtraTimeAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PasswordGameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PasswordGameSessionId");

                    b.ToTable("PasswordTeams", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.PasswordGame.PasswordWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PasswordCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PasswordCategoryId");

                    b.ToTable("PasswordWords", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PointValue")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.RankingGame.RankingCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("RankingCategories", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.RankingGame.RankingGameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("CategoryIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundsPerTeam")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RankingGameSessions", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.RankingGame.RankingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RankingCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("RankingCategoryId");

                    b.ToTable("RankingLists", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.RankingGame.RankingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectPosition")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("RankingListId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RankingListId");

                    b.HasIndex("RankingListId", "CorrectPosition")
                        .IsUnique();

                    b.ToTable("RankingListItems", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.RankingGame.RankingRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer");

                    b.Property<Guid>("RankingGameSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RankingListId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RankingGameSessionId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("RankingRounds", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.RankingGame.RankingTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RankingGameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RankingGameSessionId");

                    b.ToTable("RankingTeams", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("DoublePointsAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoAnswersAvailable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Top100Game.Top100Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Top100Categories", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Top100Game.Top100GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("CategoryIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GuessesPerTeam")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Top100GameSessions", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Top100Game.Top100Guess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GuessText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("MatchedItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Top100RoundId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Top100RoundId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("Top100Guesses", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Top100Game.Top100List", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("Top100CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Top100CategoryId");

                    b.ToTable("Top100Lists", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Top100Game.Top100ListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AlternateSpellings")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("Top100ListId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Top100ListId");

                    b.HasIndex("Top100ListId", "Position")
                        .IsUnique();

                    b.ToTable("Top100ListItems", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Top100Game.Top100Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentTurnTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("GuessesMade")
                        .HasColumnType("integer");

                    b.Property<int>("MaxGuesses")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("Top100GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Top100ListId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Top100GameSessionId")
                        .IsUnique();

                    b.ToTable("Top100Rounds", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Top100Game.Top100Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("Top100GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Top100GameSessionId");

                    b.ToTable("Top100Teams", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Categories.Category", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.GameSessions.GameQuestionState", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.GameSessions.GameSession", null)
                        .WithMany("QuestionStates")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.GameSessions.GameSession", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.PasswordGame.PasswordGameSession", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.PasswordGame.PasswordRound", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.PasswordGame.PasswordGameSession", null)
                        .WithMany("Rounds")
                        .HasForeignKey("PasswordGameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.PasswordGame.PasswordTeam", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.PasswordGame.PasswordGameSession", null)
                        .WithMany("Teams")
                        .HasForeignKey("PasswordGameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.RankingGame.RankingGameSession", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.RankingGame.RankingRound", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.RankingGame.RankingGameSession", null)
                        .WithMany("Rounds")
                        .HasForeignKey("RankingGameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.RankingGame.RankingTeam", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.RankingGame.RankingGameSession", null)
                        .WithMany("Teams")
                        .HasForeignKey("RankingGameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Teams.Team", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.GameSessions.GameSession", null)
                        .WithMany("Teams")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Top100Game.Top100GameSession", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Top100Game.Top100Guess", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.Top100Game.Top100Round", null)
                        .WithMany("Guesses")
                        .HasForeignKey("Top100RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Top100Game.Top100Round", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.Top100Game.Top100GameSession", null)
                        .WithMany("Rounds")
                        .HasForeignKey("Top100GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Top100Game.Top100Team", b =>
                {
                    b.HasOne("Jabartah.Trivia.Domain.Top100Game.Top100GameSession", null)
                        .WithMany("Teams")
                        .HasForeignKey("Top100GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.GameSessions.GameSession", b =>
                {
                    b.Navigation("QuestionStates");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.PasswordGame.PasswordGameSession", b =>
                {
                    b.Navigation("Rounds");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.RankingGame.RankingGameSession", b =>
                {
                    b.Navigation("Rounds");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Top100Game.Top100GameSession", b =>
                {
                    b.Navigation("Rounds");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Jabartah.Trivia.Domain.Top100Game.Top100Round", b =>
                {
                    b.Navigation("Guesses");
                });
#pragma warning restore 612, 618
        }
    }
}
